// AUTO-GENERATED from bounds_manifest.json. DO NOT EDIT.
pub const PRASAD_SUNITHA_PROOF_BOUND: u64 = 15;
pub const PRASAD_SUNITHA_BOUND_NO_3_5: u64 = 15;
pub const BASELINE_MIN_PRIME_FACTORS: u64 = 7;
pub const EULER_CEILING_NUM: u64 = 20442;
pub const EULER_CEILING_DEN: u64 = 10000;
