use crate::types::Uint;
use crate::types::UintExt;
use crate::lean_ffi::check_mod_8;

pub trait Obstruction: Sync + Send {
    /// Check if a prime factor `q` of `sigma(p^{2e})` is forbidden.
    fn check_prime_factor(&self, _q: u64) -> bool {
        false
    }
    
    /// Statically check if a component `p^{2e}` is forbidden based on its base and exponent.
    fn check_component(&self, _p: u64, _two_e: u32) -> bool {
        false
    }
}

pub struct Mod8Obstruction;
impl Obstruction for Mod8Obstruction {
    fn check_prime_factor(&self, q: u64) -> bool {
        let r = q % 8;
        let rust_res = r == 5 || r == 7;
        let lean_res = check_mod_8(q);
        
        debug_assert_eq!(rust_res, lean_res, "Rust and Lean disagree on Mod 8 obstruction for q={}", q);
        rust_res
    }
}

pub struct Mod3Obstruction;
impl Obstruction for Mod3Obstruction {
    /// Always allows a component check (no obstruction).
    ///
    /// This implementation ignores both `p` and `two_e` and unconditionally returns `false`,
    /// representing a pass-through (no obstruction) rule.
    ///
    /// # Examples
    ///
    /// ```
    /// let ob = Mod3Obstruction;
    /// assert_eq!(ob.check_component(7, 4), false);
    /// ```
    fn check_component(&self, _p: u64, _two_e: u32) -> bool {
        // Speculative constraints removed. Act as pass-through.
        false
    }
}

pub struct Mod5Obstruction;
impl Obstruction for Mod5Obstruction {
    fn check_component(&self, p: u64, two_e: u32) -> bool {
        // Abbott-Aull Modulo-5 obstruction
        // For a QPN, 5 cannot divide sigma(N).
        // If p = 1 mod 5, sigma(p^{2e}) = 2e + 1 mod 5.
        // So if 2e + 1 = 0 mod 5 => 2e = 4 mod 5 => e = 2 mod 5.
        // In this case, 5 divides sigma(p^{2e}), which is forbidden.
        let e = two_e / 2;
        if p % 5 == 1 && e % 5 == 2 {
            return true;
        }
        false
    }
}

pub struct Mod9Obstruction;
impl Obstruction for Mod9Obstruction {
    /// Always allows a component check (no obstruction).
    ///
    /// This implementation ignores both `p` and `two_e` and unconditionally returns `false`,
    /// representing a pass-through (no obstruction) rule.
    ///
    /// # Examples
    ///
    /// ```
    /// let ob = Mod3Obstruction;
    /// assert_eq!(ob.check_component(7, 4), false);
    /// ```
    fn check_component(&self, _p: u64, _two_e: u32) -> bool {
        // Speculative constraints removed. Act as pass-through.
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mod5_abbott_aull_obstruction() {
        let filter = Mod5Obstruction;
        // p = 11 (1 mod 5), 2e = 4 => e = 2.
        // sigma(11^4) = 16105, which is divisible by 5.
        assert!(filter.check_component(11, 4));
        // p = 11, 2e = 2 => e = 1.
        // sigma(11^2) = 133, not divisible by 5.
        assert!(!filter.check_component(11, 2));
    }

    #[test]
    fn test_mod8_obstruction() {
        let filter = Mod8Obstruction;
        assert!(filter.check_prime_factor(5));
        assert!(filter.check_prime_factor(7));
        assert!(!filter.check_prime_factor(3));
        assert!(!filter.check_prime_factor(17));
    }
    
    #[test]
    fn test_mod3_and_mod9_obstructions() {
        let mod3 = Mod3Obstruction;
        let mod9 = Mod9Obstruction;
        
        assert!(!mod3.check_component(7, 4)); // Pass-through
        assert!(!mod3.check_component(7, 2)); // Pass-through
        
        assert!(!mod9.check_component(13, 8)); // Pass-through
        assert!(!mod9.check_component(13, 2)); // Pass-through
    }
}

/// Deep Divisibility Chains
/// Recursively verifies that prime factors generated by $\sigma$ propagate their constraints.
/// For Odd Perfect Numbers (OPN), factors must be *present* in the candidate set.
/// For Quasiperfect Numbers (QPN), factors must be *disjoint* from the candidate set.
pub fn verify_deep_divisibility_chain(
    candidate_factors: &[u64],
    sigma_factors: &[u64],
    must_be_present: bool,
) -> bool {
    if must_be_present {
        // Transitive factor inclusion for OPN
        for &sf in sigma_factors {
            if !candidate_factors.contains(&sf) {
                return false;
            }
        }
        true
    } else {
        // Transitive factor exclusion for QPN
        for &sf in sigma_factors {
            if candidate_factors.contains(&sf) {
                return false;
            }
        }
        true
    }
}
